### ISSUE TITLE
Howw to run a single variant caller pipeline

### ISSUE THREAD

**Issue by jflucier** [molmicdx/mtb-pipeline#3]
Hi,

how is it possible to run only the GATK pipeline? I cannot figure out how to call scons with gatk only using help.

Also how is it possible to execute scons and passing a custom configs/settings.conf directly

thanks 
JF

**Comment by yeemey** [comment]
Hi,
I didn't configure the pipeline to run single callers since we were doing comparisons. However, to run only GATK you can comment out all the SConstruct sections that involve the other variant callers and their output. You can also make a copy of the SConstruct file with the necessary edits and tell scons to use that instead, and also pass a custom settings file like this:
```
scons -f SConstruct-new SETTINGS=configs/settings-new.conf
```

**Comment by yeemey** [comment]
For more info on scons: https://scons.org/doc/production/HTML/scons-user.html

**Comment by jflucier** [comment]
I commented out other variant caller and it work with provided data

thanks
